# Site settings
title: Magda Paraskevopoulou
description: GitHub Progile
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mauricio Urraco
user_description: A digital marketer passionate about creating impactful campaigns and connecting with audiences. Currently, expanding my skill set by learning data analytics to combine creativity with data-driven strategies. 
user_title: Digital Marketer
email: paraskevopouloumagdalini@gmail.com
# twitter_username: 
instagram_username: 
facebook_username: Magda Paraskevopoulou 
linkedin_username: Magda Paraskevopoulou
github_username:  Magdi18
# medium_username: 
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

